version: '3.9'
volumes:
  db-store:
services:
    web:
        image: nginx:1.21.6-alpine
        ports:
            - 34251:80
        volumes:
            - ./src:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
    app:
        build: ./docker/php
        volumes:
            - ./src:/var/www
            - ./src/webroot/upload/profile_img:/var/www/webroot/upload/profile_img
        links:
            - db
        depends_on:
            - db
    db:
        image: mysql:8.0.26
        platform: 'linux/amd64'
        volumes:
            - ./docker/mysql/conf.d:/etc/mysql/conf.d
            - db-store:/var/lib/mysql
        ports:
            - 2435:3306
        environment:
            - MYSQL_DATABASE=mykiji
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
            - MYSQL_ROOT_PASSWORD=password
            - TZ="Asia/Tokyo"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - db
        volumes:
            - ./docker/phpmyadmin/sessions:/sessions
        ports:
            - "3000:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOSTS=db
            - PMA_USER=user
            - PMA_PASSWORD=password
    mailhog:
        image: mailhog/mailhog
        ports:
            - "8025:8025" 
            - "1025:1025"